id: A65BCB428
title: Prayer for the Spread of the Tradition of Pegyal Lingpa
type: translation
pechas:
- I4FC55979
- I522DBDB4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:47:04.207793
  last_modified_at: 2023-01-04 11:47:04.207804
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I4FC55979/1C48: 27AE
  I522DBDB4/0670: 27AE
